spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa53j3f7yAS4kvVi4x6
            client-secret: jtwheBijkB7dTIJdFfnwYzlA1pO2u8PtKfvUBnv0
        provider:
          okta:
            authorization-uri: https://dev-981131.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-981131.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-981131.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-981131.okta.com/oauth2/default/v1/keys
